#include "token.h"

const char* token_kind_name(TokenKind kind) {
    switch (kind) {
        case TOK_EOF:       return "EOF";
        case TOK_IDENT:     return "identifier";
        case TOK_INT_LIT:   return "integer literal";
        case TOK_CHAR_LIT:  return "char literal";
        case TOK_STRING_LIT: return "string literal";
        case TOK_FLOAT_LIT: return "floating-point literal";
        case TOK_KW_U8:     return "u8";
        case TOK_KW_U16:    return "u16";
        case TOK_KW_U32:    return "u32";
        case TOK_KW_U64:    return "u64";
        case TOK_KW_I8:     return "i8";
        case TOK_KW_I16:    return "i16";
        case TOK_KW_I32:    return "i32";
        case TOK_KW_I64:    return "i64";
        case TOK_KW_F32:    return "f32";
        case TOK_KW_F64:    return "f64";
        case TOK_KW_REF:    return "ref";
        case TOK_KW_WEAK:   return "weak";
        case TOK_KW_STRUCT: return "struct";
        case TOK_KW_IF:     return "if";
        case TOK_KW_ELSE:   return "else";
        case TOK_KW_WHILE:  return "while";
        case TOK_KW_FOR:    return "for";
        case TOK_KW_FOREACH: return "foreach";
        case TOK_KW_IN:     return "in";
        case TOK_KW_RETURN: return "return";
        case TOK_KW_NEW:    return "new";
        case TOK_KW_CLASS:  return "class";
        case TOK_KW_THIS:   return "this";
        case TOK_KW_INTERFACE: return "interface";
        case TOK_KW_AS:     return "as";
        case TOK_KW_NATIVE: return "native";
        case TOK_KW_STRING: return "string";
        case TOK_KW_OVERRIDE: return "override";
        case TOK_KW_BREAK:  return "break";
        case TOK_KW_CONTINUE: return "continue";
    case TOK_KW_MATCH:  return "match";
        case TOK_KW_NULL:   return "null";
        case TOK_KW_BOOL:   return "bool";
        case TOK_KW_TRUE:   return "true";
        case TOK_KW_FALSE:  return "false";
        case TOK_KW_PUBLIC:  return "public";
        case TOK_KW_PRIVATE: return "private";
        case TOK_KW_OBJECT:  return "object";
        case TOK_KW_CONST:   return "const";
        case TOK_KW_STATIC:  return "static";
        case TOK_KW_ENUM:    return "enum";
        case TOK_KW_NAMESPACE: return "namespace";
        case TOK_PLUS:      return "+";
        case TOK_MINUS:     return "-";
        case TOK_STAR:      return "*";
        case TOK_SLASH:     return "/";
        case TOK_PERCENT:   return "%";
        case TOK_EQ:        return "==";
        case TOK_NE:        return "!=";
        case TOK_LT:        return "<";
        case TOK_LE:        return "<=";
        case TOK_GT:        return ">";
        case TOK_GE:        return ">=";
        case TOK_ASSIGN:    return "=";
        case TOK_PLUS_ASSIGN:  return "+=";
        case TOK_MINUS_ASSIGN: return "-=";
        case TOK_STAR_ASSIGN:  return "*=";
        case TOK_SLASH_ASSIGN: return "/=";
        case TOK_INC:       return "++";
        case TOK_DEC:       return "--";
        case TOK_NOT:       return "!";
        case TOK_AND:       return "&&";
        case TOK_OR:        return "||";
        case TOK_FATARROW: return "=>";
        case TOK_AMP:       return "&";
        case TOK_PIPE:      return "|";
        case TOK_CARET:     return "^";
        case TOK_TILDE:     return "~";
        case TOK_SHL:       return "<<";
        case TOK_SHR:       return ">>";
        case TOK_AMP_ASSIGN:  return "&=";
        case TOK_PIPE_ASSIGN: return "|=";
        case TOK_CARET_ASSIGN: return "^=";
        case TOK_SHL_ASSIGN:  return "<<=";
        case TOK_SHR_ASSIGN:  return ">>=";
        case TOK_LPAREN:    return "(";
        case TOK_RPAREN:    return ")";
        case TOK_LBRACE:    return "{";
        case TOK_RBRACE:    return "}";
        case TOK_LBRACKET:  return "[";
        case TOK_RBRACKET:  return "]";
        case TOK_SEMI:      return ";";
        case TOK_COMMA:     return ",";
        case TOK_DOT:       return ".";
        case TOK_COLON:     return ":";
        default:            return "?";
    }
}
